[tool.poetry]
name = "renovatetest"
version = "2.0.1"
description = "test renovate issues"
authors = []

[tool.poetry.dependencies]
python = "^3.8"
coverage = {version = "^5.0.3", extras = ["toml"]}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
